"""empty message

Revision ID: 0947d2f804f9
Revises: 
Create Date: 2021-11-14 14:58:11.276966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0947d2f804f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('incident_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('inc_mgr', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_no', name=op.f('pk_incident'))
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_inc_mgr'), ['inc_mgr'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_incident_no'), ['incident_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_incident_start_time'), ['start_time'], unique=False)

    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('primary_contact', sa.String(length=64), nullable=True),
    sa.Column('contact_number', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system'))
    )
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_contact_number'), ['contact_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_primary_contact'), ['primary_contact'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_team'), ['team'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('assignee', sa.String(length=32), nullable=True),
    sa.Column('activity', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('incident_no', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['incident_no'], ['incident.incident_no'], name=op.f('fk_event_incident_no_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_assignee'), ['assignee'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_incident_no'), ['incident_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)

    op.create_table('impact_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_no', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('submitter', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['incident_no'], ['incident.incident_no'], name=op.f('fk_impact_statement_incident_no_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_statement'))
    )
    with op.batch_alter_table('impact_statement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_statement_incident_no'), ['incident_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_statement_submitter'), ['submitter'], unique=False)

    op.create_table('inc_mem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('incident_no', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['incident_no'], ['incident.incident_no'], name=op.f('fk_inc_mem_incident_no_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inc_mem'))
    )
    with op.batch_alter_table('inc_mem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inc_mem_incident_no'), ['incident_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_inc_mem_person'), ['person'], unique=False)
        batch_op.create_index(batch_op.f('ix_inc_mem_role'), ['role'], unique=False)

    op.create_table('system_inc_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_no', sa.String(length=32), nullable=True),
    sa.Column('sysid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_no'], ['incident.incident_no'], name=op.f('fk_system_inc_rel_incident_no_incident')),
    sa.ForeignKeyConstraint(['sysid'], ['system.id'], name=op.f('fk_system_inc_rel_sysid_system')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_inc_rel'))
    )
    with op.batch_alter_table('system_inc_rel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_inc_rel_incident_no'), ['incident_no'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_no', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('assignee', sa.String(length=32), nullable=True),
    sa.Column('eta', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['incident_no'], ['incident.incident_no'], name=op.f('fk_task_incident_no_incident')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignee'), ['assignee'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_incident_no'), ['incident_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_incident_no'))
        batch_op.drop_index(batch_op.f('ix_task_assignee'))

    op.drop_table('task')
    with op.batch_alter_table('system_inc_rel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_inc_rel_incident_no'))

    op.drop_table('system_inc_rel')
    with op.batch_alter_table('inc_mem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inc_mem_role'))
        batch_op.drop_index(batch_op.f('ix_inc_mem_person'))
        batch_op.drop_index(batch_op.f('ix_inc_mem_incident_no'))

    op.drop_table('inc_mem')
    with op.batch_alter_table('impact_statement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_statement_submitter'))
        batch_op.drop_index(batch_op.f('ix_impact_statement_incident_no'))

    op.drop_table('impact_statement')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_event_incident_no'))
        batch_op.drop_index(batch_op.f('ix_event_assignee'))

    op.drop_table('event')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_team'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_primary_contact'))
        batch_op.drop_index(batch_op.f('ix_system_owner'))
        batch_op.drop_index(batch_op.f('ix_system_name'))
        batch_op.drop_index(batch_op.f('ix_system_contact_number'))
        batch_op.drop_index(batch_op.f('ix_system_contact_email'))
        batch_op.drop_index(batch_op.f('ix_system_category'))

    op.drop_table('system')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_start_time'))
        batch_op.drop_index(batch_op.f('ix_incident_incident_no'))
        batch_op.drop_index(batch_op.f('ix_incident_inc_mgr'))

    op.drop_table('incident')
    # ### end Alembic commands ###
