"""empty message

Revision ID: b7ba4aca46da
Revises: 0947d2f804f9
Create Date: 2021-12-04 14:38:08.854040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ba4aca46da'
down_revision = '0947d2f804f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_system_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_priority'))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
